# Usar una imagen base de Node.js
FROM node:22.2.0

# Argumentos de construcción
ARG PORT
ARG HOST

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Configurar las variables de entorno
ENV PORT=$PORT
ENV HOST=$HOST

# Exponer el puerto
EXPOSE $PORT

# Comando para ejecutar la aplicación
CMD ["node", "apigateway.js"]
