apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Solid IT\Documents\JC\Repositorio\Talent-Residency2\Talent-residency\back\deploys\kompose-windows-amd64.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: appointment
  name: appointment
spec:
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007
  selector:
    app: appointment
  type: LoadBalancer