version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  userservice:
    build:
      context: ../services/user-service
    environment:
      - PORT=4001
      - HOST=localhost
    ports:
      - "4001:4001"
    networks:
      - app-network

  apigateway:
    build:
      context: ../apigateway
    environment:
      - PORT=4000
      - HOST=localhost
    ports:
      - "4000:4000"
    depends_on:
      - userservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
