apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1 # Cambia según la cantidad de réplicas necesarias.
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: ankar2147/gatewey:1.0.0
          ports:
            - containerPort: 4000
              protocol: TCP
          env: # Variables de entorno
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4000"
            - name: URL_HOST
              value: DEV
          resources: # Configuración recomendada de recursos
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
