apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Solid IT\Documents\JC\Repositorio\Talent-Residency2\Talent-residency\back\deploys\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: providerservice
  name: providerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: providerservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Solid IT\Documents\JC\Repositorio\Talent-Residency2\Talent-residency\back\deploys\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: providerservice
    spec:
      containers:
        - name: providerservice
          image: ankar2147/solid:2.0.0
          env:
            - name: DB
              value: mydatabase
            - name: DB_HOST
              value: 10.242.13.1
            - name: DB_PASSWORD
              value: mypassword
            - name: DB_PORT
              value: "5432"
            - name: DB_TYPE
              value: postgres
            - name: DB_USER
              value: myuser
            - name: EMAIL_PASS
              value: oskx bcdz odyk ilpu
            - name: EMAIL_USER
              value: devsolidit@gmail.com
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4002"
          ports:
            - containerPort: 4002
              protocol: TCP
      restartPolicy: Always
